---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector-role

- name: Install Lightouse
  hosts: lighthouse
  roles:
    - lighthouse-role
